[package]
name = "termcopy"
version = "0.3.0-dev"
edition = "2021"
description = "A utility program that enables clipboard copying using OSC52 escape sequences"
repository = "https://github.com/trevorbernard/termcopy"
license = "MIT"

[dependencies]
argh = "0.1.12"
base64 = "0.22.1"

[dev-dependencies]
tempfile = "3.8"
