name: CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Install Rust toolchain
        # rustup reads the version and components from rust-toolchain.toml
        run: rustup toolchain install

      - name: Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Test
        run: cargo test
